sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -U flake8
  - pip install -U isort
  - pip install -U yapf
script:
  - find . -not -path '*/.eggs/*' -not -path './venv/*' -name '*.py' | xargs flake8
  - py.test tests/
